services:
  congenial-carnival:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGODB_CONNSTRING=mongodb://CongenialCarnival:CongenialCarnival@mongodb
  mongodb:
    image: mongo:5.0
    volumes: 
      - dbvolume1:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=CongenialCarnival
      - MONGO_INITDB_ROOT_PASSWORD=CongenialCarnival
volumes:
  dbvolume1: